### ISSUE TITLE
Update to the audiovisual art timeline - 1910s & related

### ISSUE THREAD

**Issue by l-lu-u** [aaltonewmedia/learn.newmedia.dog#4]
1915, Alexander Scriabin's synaesthetic symphony _Prometheus: The Poem of Fire_ was premiered in New York, the performance was accompanied with a colour organ/keyboard, ["Clavier à lumières"](https://en.wikipedia.org/wiki/Clavier_%C3%A0_lumi%C3%A8res), constructed by Preston S. Miller, the president of the Illuminating Engineering Society

2010, Anna Gawboy realized Alexander Scriabin's _Prometheus: The Poem of Fire_ with lighting designer Justin Townsend and [the Yale Symphony Orchestra](https://youtu.be/V3B7uQ5K0IU?feature=shared)

**Comment by mnstri** [comment]
Added, thank you!
