### ISSUE TITLE
Update to the audiovisual art timeline - 1290s or earlier

### ISSUE THREAD

**Issue by l-lu-u** [aaltonewmedia/learn.newmedia.dog#5]
~prior to 1290s, [走马灯/走馬燈](https://web.archive.org/web/20191202065903/http://hk.chiculture.net/0811/html/c36/0811c36.html) ("running-horse-lantern", similar to laterna magica) was documented in the writing of《武林舊事》:"..It looks like shadow puppets, where there are running horses and people spinning like about to fly...「……若沙戲影燈，馬騎人物，旋轉如飛。……」"

**Comment by mnstri** [comment]
Added!
